server:
  port: 9001

spring:
  application:
    name: cps-zuul
eureka:
  client:
    service-url:
      # 填写注册中心服务器地址
      defaultZone: http://localhost:8081/eureka

zuul:
  host:
    connect-timeout-millis: 15000 #HTTP连接超时要比Hystrix的大
    socket-timeout-millis: 60000   #socket超时
  routes:
#    路由名称，随意命名
    cps-user:
      path: /user/**
      serviceId: cps-user

    cps-business:
      path: /business/**
      serviceId: cps-business

    cps-config-server:
      path: /config-server/**
      serviceId: cps-config-server
#  设置不能通过服务名访问
  ignored-services: "*"

ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
